// Generated by lintskill — tuned for vibe-coded repos
// Security: strict, Style: auto-fix only, Complexity: relaxed
import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default [
  js.configs.recommended,
  {
    rules: {
      // Security
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",

      // Correctness
      "no-unused-vars": "warn",
      "no-undef": "error",
      "no-constant-condition": "warn",
      "no-unreachable": "error",

      // Style — keep lenient, don't overwhelm beginners
      "no-console": "off",
      semi: "off",
      quotes: "off",
    },
  },
  ...tseslint.configs.recommended,
  {
    ignores: [
      "node_modules/",
      "dist/",
      "build/",
      "out/",
      ".next/",
      ".turbo/",
      ".vercel/",
      ".cache/",
      "coverage/",
      ".git/",
    ],
  },
];
