import { readdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { lintLearnings } from "../learn/lint.js";
import { readLearning } from "../learn/store.js";
import type { LearningFile } from "../learn/types.js";

/**
 * The mechanical stage of an ADR 0001 consolidation pass: everything that can
 * be derived without judgment. The LLM stage (topic grouping, contradiction
 * detection, merge formulations) consumes this plus the raw learnings — see
 * generateConsolidationPrompt.
 *
 * A change set is always a PROPOSAL: producing one never mutates the store.
 */
export interface ChangeSet {
  scanned: number;
  /** Same LEARN id in more than one file — resolve by renumber or retire */
  idCollisions: { ids: string[]; files: string[]; action: "renumber-or-retire" }[];
  /** Distinct ids saying nearly the same thing — merge into one rule */
  mergeCandidates: { ids: string[]; files: string[]; similarity: string }[];
  /** Single-learning verdicts derivable mechanically */
  dispositions: { id: string; file: string; action: "rewrite-or-retire"; reason: string }[];
}

export function buildChangeSet(dir: string): ChangeSet {
  const report = lintLearnings(dir);

  const idCollisions = report.findings
    .filter((f) => f.type === "duplicate-id")
    .map((f) => ({ ids: f.ids, files: f.files, action: "renumber-or-retire" as const }));

  const mergeCandidates = report.findings
    .filter((f) => f.type === "near-duplicate")
    .map((f) => {
      const match = f.message.match(/similarity (\d+\.\d+)/);
      return { ids: f.ids, files: f.files, similarity: match ? match[1] : "n/a" };
    });

  const dispositions = report.findings
    .filter((f) => f.type === "no-trigger")
    .map((f) => ({
      id: f.ids[0],
      file: f.files[0],
      action: "rewrite-or-retire" as const,
      reason: "no checkable trigger condition",
    }));

  return { scanned: report.scanned, idCollisions, mergeCandidates, dispositions };
}

export function renderChangeSet(changeSet: ChangeSet, date: string): string {
  const lines: string[] = [
    `# Consolidation change set — ${date}`,
    "",
    "Mechanical stage output. This is a **proposal** — nothing in the store",
    "has been changed. Review, then apply decisions via the learn commands.",
    "",
  ];

  lines.push("## ID collisions (renumber or retire)", "");
  if (changeSet.idCollisions.length === 0) lines.push("- none");
  for (const c of changeSet.idCollisions) {
    lines.push(`- **${c.ids.join(", ")}**: ${c.files.join(", ")}`);
  }

  lines.push("", "## Merge candidates (near-duplicates)", "");
  if (changeSet.mergeCandidates.length === 0) lines.push("- none");
  for (const m of changeSet.mergeCandidates) {
    lines.push(`- **${m.ids.join(" + ")}** (similarity ${m.similarity}): ${m.files.join(", ")}`);
  }

  lines.push("", "## Dispositions", "");
  if (changeSet.dispositions.length === 0) lines.push("- none");
  for (const d of changeSet.dispositions) {
    lines.push(`- **${d.id}** → ${d.action}: ${d.reason} (${d.file})`);
  }

  lines.push("", `_Scanned ${changeSet.scanned} learnings. Generated by \`sheal consolidate\`._`, "");
  return lines.join("\n");
}

/**
 * The LLM stage prompt: hands the raw learnings plus the mechanical change
 * set to any agent CLI and asks for the judgment work (topic pages,
 * contradictions, merge formulations) in the reference format validated by
 * the 2026-07-06 milestone pass.
 */
export function generateConsolidationPrompt(dir: string, changeSet: ChangeSet): string {
  const learnings = listLearningsWithFiles(dir);
  const learningBlocks = learnings
    .map(
      ({ file, learning }) =>
        `### ${learning.id} (${file}) [status: ${learning.status}]\nTitle: ${learning.title}\n${learning.body}`,
    )
    .join("\n\n");

  return `You are running the judgment stage of a knowledge-consolidation pass over a
coding-agent learnings store (see the repo's ADR 0001). The mechanical stage
already ran; its change set is below. Produce, as markdown:

1. Candidate **topic pages** (4-6): name, scope, member learnings with
   provenance, proposed merged rules, and a trigger table ("when X, apply
   rule N").
2. **Contradictions**: pairs that conflict, each with a proposed precedence
   rule for human review.
3. A **per-learning disposition table**: keep / merge-into / retire, plus a
   PROSE vs MECHANICAL classification (mechanical = compilable into a hook,
   checker, or config entry — name the target).

Rules: do not invent learnings; treat the mechanical change set below as
ground truth for duplicates; every learning must appear in a topic page or be
explicitly listed as resisting grouping. The output is a proposal — never
instruct anyone to delete files directly.

## Mechanical change set
${JSON.stringify(changeSet, null, 2)}

## Learnings store
${learningBlocks}
`;
}

function listLearningsWithFiles(dir: string): { file: string; learning: LearningFile }[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.startsWith("LEARN-") && f.endsWith(".md"))
    .sort()
    .map((file) => ({ file, learning: readLearning(join(dir, file)) }));
}
